name: testcafe
description: 'hi'
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest 
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: install testcafe
        run: npm i testcafe
      - name: run tests
        run: testcafe chrome ".\tests\remote.test.js